#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ -f ".venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source ".venv/bin/activate"
fi

if [[ -f ".env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source ".env"
  set +a
fi

# shellcheck disable=SC1091
source "$ROOT_DIR/scripts/env_ffmpeg.sh"

export EM2MEM_PIPELINE_MODE="${EM2MEM_PIPELINE_MODE:-mst}"
export EM2MEM_LIVE_INGEST_FRAME_FPS="${EM2MEM_LIVE_INGEST_FRAME_FPS:-1}"
export EM2MEM_LIVE_INGEST_AUDIO_SEGMENT_MS="${EM2MEM_LIVE_INGEST_AUDIO_SEGMENT_MS:-1500}"
export EM2MEM_LIVE_INGEST_RW_TIMEOUT_US="${EM2MEM_LIVE_INGEST_RW_TIMEOUT_US:-10000000}"
export EM2MEM_LIVE_INGEST_PROBE_TIMEOUT_SECONDS="${EM2MEM_LIVE_INGEST_PROBE_TIMEOUT_SECONDS:-10}"
export EM2MEM_LIVE_INGEST_PROBE_RETRY_SECONDS="${EM2MEM_LIVE_INGEST_PROBE_RETRY_SECONDS:-2}"
export EM2MEM_LIVE_INGEST_ATTEMPT_NO_OUTPUT_SECONDS="${EM2MEM_LIVE_INGEST_ATTEMPT_NO_OUTPUT_SECONDS:-25}"
export EM2MEM_LIVE_INGEST_TOTAL_WAIT_SECONDS="${EM2MEM_LIVE_INGEST_TOTAL_WAIT_SECONDS:-90}"
export EM2MEM_ROKID_LIVE_INGEST_RW_TIMEOUT_US="${EM2MEM_ROKID_LIVE_INGEST_RW_TIMEOUT_US:-30000000}"
export EM2MEM_ROKID_LIVE_INGEST_STARTUP_WAIT_SECONDS="${EM2MEM_ROKID_LIVE_INGEST_STARTUP_WAIT_SECONDS:-120}"
export EM2MEM_ROKID_LIVE_INGEST_RECOVERY_WAIT_SECONDS="${EM2MEM_ROKID_LIVE_INGEST_RECOVERY_WAIT_SECONDS:-0}"

echo "[start_online_live_ingest_worker] EM2MEM_PIPELINE_MODE=${EM2MEM_PIPELINE_MODE}"
echo "[start_online_live_ingest_worker] EM2MEM_LIVE_INGEST_FRAME_FPS=${EM2MEM_LIVE_INGEST_FRAME_FPS}"
echo "[start_online_live_ingest_worker] EM2MEM_LIVE_INGEST_AUDIO_SEGMENT_MS=${EM2MEM_LIVE_INGEST_AUDIO_SEGMENT_MS}"
echo "[start_online_live_ingest_worker] EM2MEM_LIVE_INGEST_RW_TIMEOUT_US=${EM2MEM_LIVE_INGEST_RW_TIMEOUT_US}"
echo "[start_online_live_ingest_worker] EM2MEM_LIVE_INGEST_ATTEMPT_NO_OUTPUT_SECONDS=${EM2MEM_LIVE_INGEST_ATTEMPT_NO_OUTPUT_SECONDS}"
echo "[start_online_live_ingest_worker] EM2MEM_LIVE_INGEST_TOTAL_WAIT_SECONDS=${EM2MEM_LIVE_INGEST_TOTAL_WAIT_SECONDS}"
echo "[start_online_live_ingest_worker] EM2MEM_ROKID_LIVE_INGEST_RW_TIMEOUT_US=${EM2MEM_ROKID_LIVE_INGEST_RW_TIMEOUT_US}"
echo "[start_online_live_ingest_worker] EM2MEM_ROKID_LIVE_INGEST_STARTUP_WAIT_SECONDS=${EM2MEM_ROKID_LIVE_INGEST_STARTUP_WAIT_SECONDS}"
echo "[start_online_live_ingest_worker] EM2MEM_ROKID_LIVE_INGEST_RECOVERY_WAIT_SECONDS=${EM2MEM_ROKID_LIVE_INGEST_RECOVERY_WAIT_SECONDS}"
echo "[start_online_live_ingest_worker] EM2MEM_LIVE_PULL_BASE_URL=${EM2MEM_LIVE_PULL_BASE_URL:-}"
echo "[start_online_live_ingest_worker] task_queue_root=online_tasks/live_ingest"

exec python online_live_ingest_worker.py "$@"
