#!/usr/bin/env python3
# Derived from an external implementation; see LICENSE for attribution and upstream license terms.
# Changes made by anonymous authors

from __future__ import annotations

import argparse
import concurrent.futures
import json
import logging
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import cv2
from tqdm import tqdm

from em2mem.llm import LLMModel


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

TEXT_SYSTEM_PROMPT = """# Role and Objective

You are an expert video captioner and evidence annotator.

Your task is to transform raw video caption and transcript segments into:
1. a concise, item-focused caption that clearly describes key actions, objects, and interactions;
2. structured evidence fields that summarize salient objects, main actions, and conversation focus.

# Input Data Format

You will receive a JSON object with:
- `em2mem_caption`: the caption already generated by EM2Mem
- `transcript_entries`: a JSON array where each element has:
  - `start`: start timestamp
  - `end`: end timestamp
  - `transcript`: transcript text

# Caption Handling

- Use caption segments to anchor the visible actions, objects, tools, and interactions.
- Refine or merge redundant caption content for clarity.

# Transcript Handling

- If no transcript is provided, do not invent dialogue or conversation topics.

# Guidelines

1. Output every field in natural English only.
2. Highlight key objects, tools, or interactions.
3. Keep captions concise, direct, and focused on items or actions.
4. Merge overlapping or redundant content.
5. Ensure the final caption corresponds to the original sequence.
6. Favor clarity and succinctness over extensive narration.
7. `salient_objects` should contain concrete objects, tools, or notable items.
8. `main_actions` should be short verb phrases.
9. `conversation_focus` should summarize the main topics or requests in speech, not full transcripts. If there is no meaningful transcript evidence, return an empty list.
10. Do not invent events, objects, or speech that are not supported by the input.
11. Return valid JSON only.

# Output JSON Format

Return exactly:
{
  "fine_caption": "string",
  "salient_objects": ["..."],
  "main_actions": ["..."],
  "conversation_focus": ["..."]
}

# Examples

## Example 1
Input:
{
  "em2mem_caption": "A man opens the drawer and say, \\"Where is the scissors?\\" Then he grabs the scissors. \\"These should work,\\" The man say.",
  "transcript_entries": [
    {"start_time": 12020013, "end_time": 12020248, "transcript": "Where is the scissors?"},
    {"start_time": 12020667, "end_time": 12020743, "transcript": "These should work."}
  ]
}

Output:
{
  "fine_caption": "A man opens the drawer and say, \\"Where is the scissors?\\" Then he grabs the scissors. \\"These should work,\\" The man say.",
  "salient_objects": ["drawer", "scissors"],
  "main_actions": ["open drawer", "grab scissors", "comment on scissors"],
  "conversation_focus": ["the scissors are usable"]
}

## Example 2
Input:
{
  "wearer_name": "Jake",
  "original_em2mem_caption": "A man places the plate on the table. \\"Make sure it's centered,\\" the man say. A woman replies, \\"Got it.\\"",
  "segments": [
    {"start_time": 13031223, "end_time": 13031354, "transcript": "Make sure it's centered."},
    {"start_time": 13031534, "end_time": 13031661, "transcript": "Got it."}
  ]
}

Output:
{
  "fine_caption": "A man places the plate on the table. \\"Make sure it's centered,\\" the man say. A woman replies, \\"Got it.\\"",
  "salient_objects": ["plate", "table"],
  "main_actions": ["place plate", "give positioning instruction"],
  "conversation_focus": ["centering the plate"]
}
"""

VISUAL_SYSTEM_PROMPT = """# Role and Objective

You are an expert visual annotator.

You will be given:
- a few keyframes from a short video segment;
- a short text context for grounding only.

Your job is to describe what is visually present in the keyframes, not to paraphrase the text context.

# Instructions

1. Focus on what is actually visible in the images.
2. Do not copy the text context unless it is visually supported.
3. Use concise descriptions.
4. `scene` should be a coarse environment label such as:
   kitchen, dining area, living room, bedroom, bathroom, hallway, office/workspace,
   outdoors, store/shop, restaurant/cafe, car/interior, other
5. `keyframe_caption` should describe the visible scene.
6. `visual_objects` should contain only clearly visible objects/items.
7. Return valid JSON only.

# Output JSON Format

Return exactly:
{
  "scene": "string",
  "keyframe_caption": "string",
  "visual_objects": ["..."]
}
"""
def strip_code_fences(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    return text.strip()

def str_time_to_hhmmsscc(time_str: str) -> str:
    return time_str.replace(':', '').replace(',', '')[:-1]

def centis_to_code(cs: int) -> str:
    hh = cs // 360000
    rem = cs % 360000
    mm = rem // 6000
    rem %= 6000
    ss = rem // 100
    cc = rem % 100
    return f"{hh:02d}{mm:02d}{ss:02d}{cc:02d}"

def read_srt(srt_path: str) -> List[Dict[str, str]]:
    """
    read srt file and return a list of entries with format:
    {
        'start_time': 'HHMMSSCC',
        'end_time':   'HHMMSSCC',
        'transcript': 'transcript text'
    }
    """
    with open(srt_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    entries = []
    i = 0
    while i < len(lines):
        # skip empty lines
        if not lines[i].strip():
            i += 1
            continue

        # index line, can be ignored
        i += 1
        if i >= len(lines):
            break

        # time line, format: start --> end
        time_line = lines[i].strip()
        i += 1
        time_match = re.match(r'(\S+)\s*-->\s*(\S+)', time_line)
        if not time_match:
            continue
        start_str, end_str = time_match.groups()

        # transcript lines, can be multiple until the next empty line
        text_lines = []
        while i < len(lines) and lines[i].strip():
            text_lines.append(lines[i].strip())
            i += 1
        transcript = ' '.join(text_lines)

        entries.append({
            'start_time': str_time_to_hhmmsscc(start_str),
            'end_time': str_time_to_hhmmsscc(end_str),
            'transcript': transcript
        })

    return entries

def normalize_list_str(values: Any) -> List[str]:
    if not isinstance(values, list):
        return []
    out = []
    seen = set()
    for v in values:
        if not isinstance(v, str):
            continue
        s = v.strip()
        if not s:
            continue
        key = s.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(s)
    return out

def run_text_enrichment(model: LLMModel, em2mem_caption: str, transcript_entries: List[Dict[str, str]]) -> Dict[str, Any]:
    """use em2mem_caption and transcript_entries to generate fine_caption, salient_objects, main_actions, conversation_focus"""
    payload = {
        "em2mem_caption": em2mem_caption,
        "transcript_entries": transcript_entries
    }
    prompt = [
        {"role": "system", "content": TEXT_SYSTEM_PROMPT},
        {"role": "user", "content": json.dumps(payload, ensure_ascii=False, indent=2)}
    ]
    response = model.generate(prompt)
    data = json.loads(strip_code_fences(response))

    fine_caption = str(data.get("fine_caption", "")).strip()
    if not fine_caption:
        raise ValueError("Missing fine_caption in text enrichment output.")

    return {
        "fine_caption": fine_caption,
        "salient_objects": normalize_list_str(data.get("salient_objects")),
        "main_actions": normalize_list_str(data.get("main_actions")),
        "conversation_focus": normalize_list_str(data.get("conversation_focus")),
    }

def extract_keyframes(video_path: Path, start_cs: int, end_cs: int, frames_dir: Path, num_keyframes: int = 3) -> List[Path]:
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open video: {video_path}")

    # try to get FPS, but if it fails, default to 30
    fps = cap.get(cv2.CAP_PROP_FPS)
    if fps is None or fps <= 0:
        fps = 30.0
    
    # convert centiseconds to seconds, and ensure end is after start
    start_sec = start_cs / 100.0
    end_sec = end_cs / 100.0
    if end_sec <= start_sec:
        end_sec = start_sec + 1.0

    # get total frames and duration to ensure start/end are within bounds
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    duration_sec = total_frames / fps if fps > 0 else 0
    if duration_sec > 0:
        start_sec = max(0.0, min(start_sec, duration_sec - 1e-3))
        end_sec = max(start_sec + 1e-3, min(end_sec, duration_sec))
    else:
        start_sec = 0.0
        end_sec = 1.0

    # if the segment is too short, just take the middle frame; otherwise, sample evenly across the segment
    if num_keyframes <= 1:
        ts_list = [(start_sec + end_sec) / 2.0]
    else:
        ts_list = [start_sec + (end_sec - start_sec) * i / (num_keyframes - 1) for i in range(num_keyframes)]

    out_paths: List[Path] = []
    stem = f"{video_path.stem}_{centis_to_code(start_cs)}_{centis_to_code(end_cs)}"
    # extract and save keyframes
    for idx, ts in enumerate(ts_list):
        frame_id = int(round(ts * fps))
        frame_id = max(0, min(frame_id, max(0, total_frames - 1)))
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_id)
        ok, frame = cap.read()
        if not ok or frame is None:
            continue
        out_path = frames_dir / f"{stem}_kf{idx+1}.jpg"
        cv2.imwrite(str(out_path), frame)
        out_paths.append(out_path)

    cap.release()

    if not out_paths:
        raise RuntimeError(f"Failed to extract keyframes from {video_path}")
    return out_paths

def parse_time_code(t: Any) -> Optional[int]:
    """
    Support both:
    - HHMMSS     (e.g. 110943 from sync files)
    - HHMMSSCC   (e.g. 11094300 from EM2Mem json)
    Return centiseconds from 00:00:00.00
    """
    if t is None:
        return None

    s = re.sub(r"\D", "", str(t))
    if not s:
        return None

    if len(s) == 6:
        # HHMMSS
        hh = int(s[0:2])
        mm = int(s[2:4])
        ss = int(s[4:6])
        cc = 0
    elif len(s) == 8:
        # HHMMSSCC
        hh = int(s[0:2])
        mm = int(s[2:4])
        ss = int(s[4:6])
        cc = int(s[6:8])
    else:
        # fallback: try to interpret right-aligned, but prefer common cases above
        if len(s) < 6:
            return None
        if len(s) == 7:
            # treat as HHMMSSC (rare / malformed), append 0
            s = s + "0"
        elif len(s) > 8:
            s = s[-8:]

        if len(s) == 6:
            hh = int(s[0:2])
            mm = int(s[2:4])
            ss = int(s[4:6])
            cc = 0
        elif len(s) == 8:
            hh = int(s[0:2])
            mm = int(s[2:4])
            ss = int(s[4:6])
            cc = int(s[6:8])
        else:
            return None

    return (((hh * 60) + mm) * 60 + ss) * 100 + cc

def build_visual_prompt(keyframe_paths: List[Path], em2mem_caption: str, transcript_text: str,) -> List[Dict[str, Any]]:
    """Build the prompt for visual enrichment, including the system prompt and user content with keyframe images and text context."""
    context = {
        "text_context": {
            "em2mem_caption": em2mem_caption,
            "transcript_text": transcript_text,
        },
        "instruction": (
            "Use the text only as weak context. "
            "Describe only what is visually supported by the images. "
            "Do not paraphrase the text unless visible."
        ),
    }

    user_content: List[Dict[str, Any]] = [
        {"type": "text", "text": json.dumps(context, ensure_ascii=False, indent=2)}
    ]
    for p in keyframe_paths:
        user_content.append({"type": "image", "image": str(p)})

    return [
        {"role": "system", "content": VISUAL_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]

def run_visual_enrichment(model: LLMModel, keyframe_paths: List[Path], em2mem_caption: str, transcript_text: str,) -> Dict[str, Any]:
    """use keyframe_paths, em2mem_caption, transcript_text to generate scene, keyframe_caption, visual_objects"""
    prompt = build_visual_prompt(
        keyframe_paths=keyframe_paths,
        em2mem_caption=em2mem_caption,
        transcript_text=transcript_text,
    )
    resp = model.generate(prompt)
    data = json.loads(strip_code_fences(resp))

    scene = str(data.get("scene", "")).strip()
    keyframe_caption = str(data.get("keyframe_caption", "")).strip()
    visual_objects = normalize_list_str(data.get("visual_objects"))

    if not scene or not keyframe_caption:
        raise ValueError("Visual enrichment missing scene or keyframe_caption.")

    return {
        "scene": scene,
        "keyframe_caption": keyframe_caption,
        "visual_objects": visual_objects,
    }

def process_video(video_file: Path, transcript_file: Path, caption_file: Path, output_file: Path, frames_dir: Path,
                  llm_text: LLMModel, llm_visual: LLMModel, num_keyframes: int, max_workers: int = None) -> None:
    frames_dir.mkdir(parents=True, exist_ok=True)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with caption_file.open("r", encoding="utf-8") as f:
        caption_data = json.load(f)
    
    transcripts = read_srt(transcript_file)

    # match transcripts to caption segments
    i = 0
    relevant_transcripts = []
    for caption_entry in caption_data:
        selected_transcripts = []
        while i < len(transcripts) and transcripts[i]['start_time'] < caption_entry['start_time']:
            i += 1
        while i < len(transcripts) and transcripts[i]['start_time'] >= caption_entry['start_time'] and transcripts[i]['end_time'] <= caption_entry['end_time']:
            selected_transcripts.append(transcripts[i])
            i += 1
        relevant_transcripts.append(selected_transcripts)
    
    # define a function to process each segment, which can be parallelized
    def process_segment(idx, cap_entry, trans_entries):
        # text augmentation
        fine_caption = cap_entry['text'].strip()
        salient_objects, main_actions, conversation_focus = [], [], []
        text_status = "kept_em2mem"
        try:
            text_out = run_text_enrichment(
                model=llm_text,
                em2mem_caption=fine_caption,
                transcript_entries=trans_entries,
            )
            fine_caption = text_out['fine_caption']
            salient_objects = text_out['salient_objects']
            main_actions = text_out['main_actions']
            conversation_focus = text_out['conversation_focus']
            text_status = "success"
        except Exception as e:
            logger.warning(f"Text enrichment failed for segment {idx} in video {video_file.stem}: {e}")
        
        # visual augmentation
        scene = ""
        keyframe_caption = ""
        visual_objects: List[str] = []
        visual_status = "failed"
        keyframe_paths_str: List[str] = []
        transcript_text = " ".join([t['transcript'] for t in trans_entries])
        try:
            keyframe_paths = extract_keyframes(
                video_path=video_file,
                start_cs=parse_time_code(cap_entry['start_time']),
                end_cs=parse_time_code(cap_entry['end_time']),
                frames_dir=frames_dir,
                num_keyframes=num_keyframes,
            )
            keyframe_paths_str = [str(p) for p in keyframe_paths]

            visual_out = run_visual_enrichment(
                model=llm_visual,
                keyframe_paths=keyframe_paths,
                em2mem_caption=fine_caption,
                transcript_text=transcript_text
            )
            scene = visual_out['scene']
            keyframe_caption = visual_out['keyframe_caption']
            visual_objects = visual_out['visual_objects']
            visual_status = "success"
        except Exception as e:
            logger.warning(f"Visual enrichment failed for segment {idx} in video {video_file.stem}: {e}")
        
        out = {
            "doc_id": f"DAY1_{cap_entry['start_time']}_{cap_entry['end_time']}",
            "date": "DAY1",
            "video_path": str(video_file),
            "start_time": cap_entry['start_time'],
            "end_time": cap_entry['end_time'],
            "caption_text": fine_caption,
            "transcript_text": transcript_text,
            "fine_caption": fine_caption,
            "scene": scene,
            "keyframe_caption": keyframe_caption,
            "visual_objects": visual_objects,
            "salient_objects": salient_objects,
            "main_actions": main_actions,
            "conversation_focus": conversation_focus,
            "speakers": [],
            "source_types": ["caption", "transcript", "em2mem_caption", "keyframes"],
            "raw_entries": trans_entries,
            "keyframe_paths": keyframe_paths_str,
            "text_enrichment_status": text_status,
            "visual_status": visual_status,
            "provenance": {
                "em2mem_input_used": True,
                "matched_sync_file": "",
                "sync_match_status": "matched",
            },
        }
        return idx, out
    
    # process segments in parallel and collect outputs in original order
    outputs = [None] * len(caption_data)
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(process_segment, idx, cap_entry, trans_entries): idx
            for idx, (cap_entry, trans_entries) in enumerate(zip(caption_data, relevant_transcripts))
        }
        for future in tqdm(concurrent.futures.as_completed(futures), total=len(futures), desc=f"Processing segments in {video_file.stem}"):
            idx, out = future.result()
            outputs[idx] = out
    
    outputs = [out for out in outputs if out is not None]
    outputs.sort(key=lambda x: parse_time_code(x["start_time"]))
    with output_file.open("w", encoding="utf-8") as f:
        json.dump(outputs, f, ensure_ascii=False, indent=2)

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate fine captions from videos and transcripts.")
    parser.add_argument("--video-path", type=Path, default=Path("data/Video-MME/data"), help="Path to a video file or a directory of videos.")
    parser.add_argument("--transcript-path", type=Path, default=Path("data/Video-MME/transcript"), help="Path to an `.srt` file or a directory of transcripts.")
    parser.add_argument("--caption-path", type=Path, default=Path("data/Video-MME/caption"), help="Path to an existing caption file or directory.")
    parser.add_argument("--output-path", type=Path, default=Path("output/videomme/metadata/multimodal_memory_cell"), help="Directory to save the generated multimodal event records.")
    parser.add_argument("--frames-dir", type=Path, default=Path("tmp/keyframes_aug"), help="Directory to save extracted keyframes.")
    parser.add_argument("--num-keyframes", type=int, default=3, help="Number of keyframes to extract per segment.")
    parser.add_argument("--model", type=str, default="gpt-5-mini", help="LLM model name.")
    parser.add_argument("--max-workers", type=int, default=None, help="Maximum number of parallel workers for processing multiple videos.")
    args = parser.parse_args()

    # get all video names from video_path
    all_video_names = []
    for file_path in args.video_path.iterdir():
        if file_path.is_file():
            all_video_names.append(file_path.stem)
    all_video_names.sort()
    
    llm_text = LLMModel(model_name=args.model)
    llm_visual = LLMModel(model_name=args.model)

    for video_name in tqdm(all_video_names, desc="Processing videos"):
        video_file = args.video_path / f"{video_name}.mp4"
        transcript_file = args.transcript_path / f"{video_name}.srt"
        caption_file = args.caption_path / video_name / "10sec.json"
        output_file = args.output_path / video_name / "multimodal_event_record.json"
        frame_dir = args.frames_dir / video_name

        if output_file.exists():
            logger.info(f"Output already exists for {video_name}, skipping.")
            continue
        
        process_video(video_file, transcript_file, caption_file, output_file, frame_dir,
                        llm_text, llm_visual, args.num_keyframes, args.max_workers)

if __name__ == "__main__":
    main()